#[general]
#live_config_reload = true

[window]
padding = {x=2, y=2}

[font]
normal = { family="JetBrains Mono" }
size = 9

[cursor]
style = { shape="Beam", blinking="On" }
blink_interval = 300
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
